# Generated by Django 4.1.5 on 2023-03-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='user.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Test_id', models.AutoField(primary_key=True, serialize=False)),
                ('Test_file_addr', models.CharField(max_length=100)),
                ('Test_type', models.SmallIntegerField(choices=[(0, 'Checkstyle'), (1, 'FindBugs'), (2, 'submit')], verbose_name='type')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Program', to='program.program')),
            ],
        ),
    ]
