# Generated by Django 4.1.7 on 2023-04-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_test_result_file_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Test_text',
            field=models.TextField(default='default', verbose_name='text'),
        ),
    ]
